---
title: "Untitled"
author: "21900230_남건욱"
date: "2023-05-06"
output: html_document
---

```{r}

PRSA_data <- read.csv("PRSA_data-2.csv")

library(dplyr)

glimpse(PRSA_data)

```

```{r}
table(PRSA_data$year)

```
```{r}

PRSA_data_train <- PRSA_data %>%
  filter(year %in% c(2010, 2011, 2012, 2013))
  
PRSA_data_test <- PRSA_data %>%
  filter(year == 2014)
  
```


```{r}

PRSA_data_train <- na.omit(PRSA_data_train)

PRSA_data_test <- na.omit(PRSA_data_test)

sum(is.na(PRSA_data_train))

sum(is.na(PRSA_data_test))
```
```{r}

dim(PRSA_data_train)

dim(PRSA_data_test)

dim(PRSA_data_test)[1]/(dim(PRSA_data_train)[1]+dim(PRSA_data_test)[1])

```


```{r}

mean(PRSA_data_train$pm2.5)

mean(PRSA_data_test$pm2.5)


var(PRSA_data_train$pm2.5)

var(PRSA_data_test$pm2.5)

c(summary(PRSA_data_train$pm2.5), "var" = var(PRSA_data_train$pm2.5))


```

```{r}
library(graphics)

# train 데이터의 pm2.5에 대한 밀도 그래프를 검은색으로 그립니다.
dens_train <- density(PRSA_data_train$pm2.5)
plot(dens_train, col = "black", main = "distribution of pm2.5 of train(black) and test(red) data")

# test 데이터의 pm2.5에 대한 밀도 그래프를 빨간색으로 그립니다.
dens_test <- density(PRSA_data_test$pm2.5)
lines(dens_test, col = "red")
```

```{r}
summary(PRSA_data_train$pm2.5)

summary(PRSA_data_test$pm2.5)


```


```{r}
#2-1
sv_reg_month <- tapply(PRSA_data_train$pm2.5, PRSA_data_train$month, mean)


PRSA_data_train$pred_month <- sv_reg_pm[PRSA_data_train$month]

PRSA_data_train$error_month <- PRSA_data_train$pm2.5 - PRSA_data_train$pred

head(PRSA_data_train[,c('month', 'pm2.5', 'pred_month', 'error_month')], 10)
```

```{r}
#2-1

PRSA_data_test$pred_month <- sv_reg_pm[PRSA_data_test$month]

PRSA_data_test$error_month <- PRSA_data_test$pm2.5 - PRSA_data_test$pred

head(PRSA_data_test[,c('month', 'pm2.5', 'pred_month', 'error_month')], 10)

```

```{r}
#2-2
mse_train_month <- mean(PRSA_data_train$error_month**2)
mse_train_month

rmse_train_month <- sqrt(mse_train)
rmse_train_month

mse_test_month <- mean(PRSA_data_test$error_month**2)
mse_test_month

rmse_test_month <- sqrt(mse_test)
rmse_test_month

msg_train_month <- sprintf("train data: (MSE %.3f) (RMSE %.3f)", mse_train_month, rmse_train_month)

print(msg_train_month)

msg_test_month <- sprintf("test data: (MSE %.3f) (RMSE %.3f)", mse_test_month, rmse_test_month)

print(msg_test_month)
```

```{r}
#2-3
RSS_train_month <- sum(PRSA_data_train$error_month**2)

SStot_train <- sum((PRSA_data_train$pm2.5 - mean(PRSA_data_train$pm2.5))**2)

Rsq_train_month <- 1- RSS_train_month/SStot_train

RSS_test_month <- sum(PRSA_data_test$error_month**2)

SStot_test <- sum((PRSA_data_test$pm2.5 - mean(PRSA_data_test$pm2.5))**2)

Rsq_test_month <- 1- RSS_test_month/SStot_test


msg_train_month2 <- sprintf("R2 for train data: %.3f", Rsq_train_month)

msg_test_month2 <- sprintf("R2 for test data: %.3f", Rsq_test_month)

print(msg_train_month2)
print(msg_test_month2)

```

```{r}

#  (R-squared) 값이 0.017이라는 것은 단일 변수 모델에서 독립 변수인 month가 pm2.5의 변동을 매우 약하게 설명하고 있음을 나타냅니다. 즉, 모델이 예측하고자 하는 종속 변수인 pm2.5의 변동 중 매우 적은 부분이 독립 변수 month로 설명될 수 있으며, 이 모델로부터 예측된 값이 실제 값과 큰 차이를 보일 가능성이 높습니다. 따라서 이 모델은 적합하지 않을 수 있으며, 추가적인 독립 변수나 다른 모델링 방법을 고려해볼 필요가 있습니다.

```

```{r}
#3
summary(PRSA_data_train$hour)

summary(PRSA_data_test$hour)


```

```{r}
#3

PRSA_data_train$hour_grp <- cut(PRSA_data_train$hour, 
                          breaks = c(0, 6, 12, 18, 24),
                          labels = c('dawn', 'morning', 'afternoon', 'night'),
                          right = F)
PRSA_data_test$hour_grp <- cut(PRSA_data_test$hour, 
                           breaks = c(0, 6, 12, 18, 24),
                           labels = c('dawn', 'morning', 'afternoon', 'night'),
                           right = F)


```

```{r}
#3-1

sv_reg_hour <- tapply(PRSA_data_train$pm2.5, PRSA_data_train$hour_grp, mean)

PRSA_data_train$pred_hour <- sv_reg_hour[PRSA_data_train$hour_grp]

PRSA_data_train$error_hour <- PRSA_data_train$pm2.5 - PRSA_data_train$pred_hour

head(PRSA_data_train[,c('hour', 'pm2.5', 'pred_hour', 'error_hour')], 10)

PRSA_data_test$pred_hour <- sv_reg_hour[PRSA_data_test$hour_grp]

PRSA_data_test$error_hour <- PRSA_data_test$pm2.5 - PRSA_data_test$pred_hour

head(PRSA_data_test[,c('hour', 'pm2.5', 'pred_hour', 'error_hour')], 10)

```

```{r}
#3-2
mse_train_hour <- mean(PRSA_data_train$error_hour**2)
mse_train_hour

rmse_train_hour <- sqrt(mse_train_hour)
rmse_train_hour

mse_test_hour <- mean(PRSA_data_test$error_hour**2)
mse_test_hour

rmse_test_hour <- sqrt(mse_test_hour)
rmse_test_hour

msg_train_hour <- sprintf("train data: (MSE %.3f) (RMSE %.3f)", mse_train_hour, rmse_train_hour)

print(msg_train_hour)

msg_test_hour <- sprintf("test data: (MSE %.3f) (RMSE %.3f)", mse_test_hour, rmse_test_hour)

print(msg_test_hour)


```

```{r}
#3-3
RSS_train_hour <- sum(PRSA_data_train$error_hour**2)

SStot_train <- sum((PRSA_data_train$pm2.5 - mean(PRSA_data_train$pm2.5))**2)

Rsq_train_hour <- 1- RSS_train_hour/SStot_train

RSS_test_hour <- sum(PRSA_data_test$error_hour**2)

SStot_test <- sum((PRSA_data_test$pm2.5 - mean(PRSA_data_test$pm2.5))**2)

Rsq_test_hour <- 1- RSS_test_hour/SStot_test


msg_train_hour2 <- sprintf("R2 for train data: %.3f", Rsq_train_hour)

msg_test_hour2 <- sprintf("R2 for test data: %.3f", Rsq_test_hour)

print(msg_train_hour2)
print(msg_test_hour2)

```

```{r}
#3
PRSA_data_train$hour_grp <- cut(PRSA_data_train$hour, 
                          breaks = c(0, 12, 24),
                          labels = c('am', 'pm'),
                          right = F)
PRSA_data_test$hour_grp <- cut(PRSA_data_test$hour, 
                           breaks = c(0, 12, 24),
                           labels = c('am', 'pm'),
                           right = F)

sv_reg_hour <- tapply(PRSA_data_train$pm2.5, PRSA_data_train$hour_grp, mean)

PRSA_data_train$pred_hour <- sv_reg_hour[PRSA_data_train$hour_grp]

PRSA_data_train$error_hour <- PRSA_data_train$pm2.5 - PRSA_data_train$pred_hour

head(PRSA_data_train[,c('hour', 'pm2.5', 'pred_hour', 'error_hour')], 10)

PRSA_data_test$pred_hour <- sv_reg_hour[PRSA_data_test$hour_grp]

PRSA_data_test$error_hour <- PRSA_data_test$pm2.5 - PRSA_data_test$pred_hour

head(PRSA_data_test[,c('hour', 'pm2.5', 'pred_hour', 'error_hour')], 10)

mse_train_hour <- mean(PRSA_data_train$error_hour**2)
mse_train_hour

rmse_train_hour <- sqrt(mse_train_hour)
rmse_train_hour

mse_test_hour <- mean(PRSA_data_test$error_hour**2)
mse_test_hour

rmse_test_hour <- sqrt(mse_test_hour)
rmse_test_hour

msg_train_hour <- sprintf("train data: (MSE %.3f) (RMSE %.3f)", mse_train_hour, rmse_train_hour)

print(msg_train_hour)

msg_test_hour <- sprintf("test data: (MSE %.3f) (RMSE %.3f)", mse_test_hour, rmse_test_hour)

print(msg_test_hour)

RSS_train_hour <- sum(PRSA_data_train$error_hour**2)

SStot_train <- sum((PRSA_data_train$pm2.5 - mean(PRSA_data_train$pm2.5))**2)

Rsq_train_hour <- 1- RSS_train_hour/SStot_train

RSS_test_hour <- sum(PRSA_data_test$error_hour**2)

SStot_test <- sum((PRSA_data_test$pm2.5 - mean(PRSA_data_test$pm2.5))**2)

Rsq_test_hour <- 1- RSS_test_hour/SStot_test


msg_train_hour2 <- sprintf("R2 for train data: %.3f", Rsq_train_hour)

msg_test_hour2 <- sprintf("R2 for test data: %.3f", Rsq_test_hour)

print(msg_train_hour2)
print(msg_test_hour2)

```

```{r}
#3
PRSA_data_train$hour_grp <- cut(PRSA_data_train$hour, 
                          breaks = c(0, 4, 8, 12, 16, 20, 24),
                          labels = c('4/24', '8/24', '12/24', '16/24', '20/24', '24/24'),
                          right = F)
PRSA_data_test$hour_grp <- cut(PRSA_data_test$hour, 
                           breaks = c(0, 4, 8, 12, 16, 20, 24),
                           labels = c('4/24', '8/24', '12/24', '16/24', '20/24', '24/24'),
                           right = F)

sv_reg_hour <- tapply(PRSA_data_train$pm2.5, PRSA_data_train$hour_grp, mean)

PRSA_data_train$pred_hour <- sv_reg_hour[PRSA_data_train$hour_grp]

PRSA_data_train$error_hour <- PRSA_data_train$pm2.5 - PRSA_data_train$pred_hour

head(PRSA_data_train[,c('hour', 'pm2.5', 'pred_hour', 'error_hour')], 10)

PRSA_data_test$pred_hour <- sv_reg_hour[PRSA_data_test$hour_grp]

PRSA_data_test$error_hour <- PRSA_data_test$pm2.5 - PRSA_data_test$pred_hour

head(PRSA_data_test[,c('hour', 'pm2.5', 'pred_hour', 'error_hour')], 10)

mse_train_hour <- mean(PRSA_data_train$error_hour**2)
mse_train_hour

rmse_train_hour <- sqrt(mse_train_hour)
rmse_train_hour

mse_test_hour <- mean(PRSA_data_test$error_hour**2)
mse_test_hour

rmse_test_hour <- sqrt(mse_test_hour)
rmse_test_hour

msg_train_hour <- sprintf("train data: (MSE %.3f) (RMSE %.3f)", mse_train_hour, rmse_train_hour)

print(msg_train_hour)

msg_test_hour <- sprintf("test data: (MSE %.3f) (RMSE %.3f)", mse_test_hour, rmse_test_hour)

print(msg_test_hour)

RSS_train_hour <- sum(PRSA_data_train$error_hour**2)

SStot_train <- sum((PRSA_data_train$pm2.5 - mean(PRSA_data_train$pm2.5))**2)

Rsq_train_hour <- 1- RSS_train_hour/SStot_train

RSS_test_hour <- sum(PRSA_data_test$error_hour**2)

SStot_test <- sum((PRSA_data_test$pm2.5 - mean(PRSA_data_test$pm2.5))**2)

Rsq_test_hour <- 1- RSS_test_hour/SStot_test


msg_train_hour2 <- sprintf("R2 for train data: %.3f", Rsq_train_hour)

msg_test_hour2 <- sprintf("R2 for test data: %.3f", Rsq_test_hour)

print(msg_train_hour2)
print(msg_test_hour2)


```

```{r}

PRSA_data_train$hour_grp <- cut(PRSA_data_train$hour, 
                          breaks = c(0, 3, 6, 9, 12, 15, 18, 21, 24),
                          labels = c('3/24', '6/24', '9/24', '12/24', '15/24', '18/24', '21/24', '24/24'),
                          right = F)
PRSA_data_test$hour_grp <- cut(PRSA_data_test$hour, 
                           breaks = c(0, 6, 9, 8, 12, 15, 18, 21, 24),
                           labels = c('3/24', '6/24', '9/24', '12/24', '15/24', '18/24', '21/24', '24/24'),
                           right = F)

sv_reg_hour <- tapply(PRSA_data_train$pm2.5, PRSA_data_train$hour_grp, mean)

PRSA_data_train$pred_hour <- sv_reg_hour[PRSA_data_train$hour_grp]

PRSA_data_train$error_hour <- PRSA_data_train$pm2.5 - PRSA_data_train$pred_hour

head(PRSA_data_train[,c('hour', 'pm2.5', 'pred_hour', 'error_hour')], 10)

PRSA_data_test$pred_hour <- sv_reg_hour[PRSA_data_test$hour_grp]

PRSA_data_test$error_hour <- PRSA_data_test$pm2.5 - PRSA_data_test$pred_hour

head(PRSA_data_test[,c('hour', 'pm2.5', 'pred_hour', 'error_hour')], 10)

mse_train_hour <- mean(PRSA_data_train$error_hour**2)
mse_train_hour

rmse_train_hour <- sqrt(mse_train_hour)
rmse_train_hour

mse_test_hour <- mean(PRSA_data_test$error_hour**2)
mse_test_hour

rmse_test_hour <- sqrt(mse_test_hour)
rmse_test_hour

msg_train_hour <- sprintf("train data: (MSE %.3f) (RMSE %.3f)", mse_train_hour, rmse_train_hour)

print(msg_train_hour)

msg_test_hour <- sprintf("test data: (MSE %.3f) (RMSE %.3f)", mse_test_hour, rmse_test_hour)

print(msg_test_hour)

RSS_train_hour <- sum(PRSA_data_train$error_hour**2)

SStot_train <- sum((PRSA_data_train$pm2.5 - mean(PRSA_data_train$pm2.5))**2)

Rsq_train_hour <- 1- RSS_train_hour/SStot_train

RSS_test_hour <- sum(PRSA_data_test$error_hour**2)

SStot_test <- sum((PRSA_data_test$pm2.5 - mean(PRSA_data_test$pm2.5))**2)

Rsq_test_hour <- 1- RSS_test_hour/SStot_test


msg_train_hour2 <- sprintf("R2 for train data: %.3f", Rsq_train_hour)

msg_test_hour2 <- sprintf("R2 for test data: %.3f", Rsq_test_hour)

print(msg_train_hour2)
print(msg_test_hour2)

summary(PRSA_data_train$hour_grp)

```

```{r}
#4
table(PRSA_data$DEWP)
summary(PRSA_data$DEWP)

```

```{r}
#4
PRSA_data_train$DEWP_grp <- cut(PRSA_data_train$DEWP, 
                          breaks = c(-40, -12, -1, 8, 17, 29),
                          labels = c('very low', 'low', 'middle', 'high', 'very high'),
                          right = F)
PRSA_data_test$DEWP_grp <- cut(PRSA_data_test$DEWP, 
                           breaks = c(-40, -12, -1, 8, 17, 29),
                           labels = c('very low', 'low', 'middle', 'high', 'very high'),
                           right = F)


sv_reg_DEWP <- tapply(PRSA_data_train$pm2.5, PRSA_data_train$DEWP_grp, mean)

PRSA_data_train$pred_DEWP <- sv_reg_DEWP[PRSA_data_train$DEWP_grp]

PRSA_data_train$error_DEWP <- PRSA_data_train$pm2.5 - PRSA_data_train$pred_DEWP

head(PRSA_data_train[,c('hour', 'pm2.5', 'pred_hour', 'error_hour')], 10)

PRSA_data_test$pred_DEWP <- sv_reg_DEWP[PRSA_data_test$DEWP_grp]

PRSA_data_test$error_DEWP <- PRSA_data_test$pm2.5 - PRSA_data_test$pred_DEWP

head(PRSA_data_test[,c('hour', 'pm2.5', 'pred_DEWP', 'error_DEWP')], 10)

mse_train_DEWP <- mean(PRSA_data_train$error_DEWP**2)
mse_train_DEWP

rmse_train_DEWP <- sqrt(mse_train_DEWP)
rmse_train_DEWP

mse_test_DEWP <- mean(PRSA_data_test$error_DEWP**2)
mse_test_DEWP

rmse_test_DEWP <- sqrt(mse_test_DEWP)
rmse_test_DEWP

msg_train_DEWP <- sprintf("train data: (MSE %.3f) (RMSE %.3f)", mse_train_DEWP, rmse_train_DEWP)

print(msg_train_DEWP)

msg_test_DEWP <- sprintf("test data: (MSE %.3f) (RMSE %.3f)", mse_test_DEWP, rmse_test_DEWP)

print(msg_test_DEWP)

RSS_train_DEWP <- sum(PRSA_data_train$error_DEWP**2)

SStot_train <- sum((PRSA_data_train$pm2.5 - mean(PRSA_data_train$pm2.5))**2)

Rsq_train_DEWP <- 1- RSS_train_DEWP/SStot_train

RSS_test_DEWP <- sum(PRSA_data_test$error_DEWP**2)

SStot_test <- sum((PRSA_data_test$pm2.5 - mean(PRSA_data_test$pm2.5))**2)

Rsq_test_DEWP <- 1- RSS_test_DEWP/SStot_test


msg_train_DEWP2 <- sprintf("R2 for train data: %.3f", Rsq_train_DEWP)

msg_test_DEWP2 <- sprintf("R2 for test data: %.3f", Rsq_test_DEWP)

print(msg_train_DEWP2)
print(msg_test_DEWP2)

summary(PRSA_data_train$DEWPㄴ_grp)
ㄴ
```

```{r}

#DEWP 가 가장 정확도가 높았음.
#R**2 와 RMSE 는 분산과 관련이 있다.
```